// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Gurkhas Store",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
    
//     <html lang="en">
//       <link rel="icon" href="/icon.png" />
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gurkha Supermarket - Your Trusted Nepali Grocery Store in Australia",
  description: "Shop for authentic Nepali groceries at Gurkha Supermarket. Fresh produce, spices, and more delivered across Australia.",
  keywords: "Nepali grocery, Nepali food, Gurkha Supermarket, grocery store Australia, Nepali spices, Nepali products",
  openGraph: {
    title: "Gurkha Supermarket - Your Trusted Nepali Grocery Store in Australia",
    description: "Shop for authentic Nepali groceries at Gurkha Supermarket. Fresh produce, spices, and more delivered across Australia.",
    url: "https://www.gurkhasupermarket.com",
    type: "website",
    image: "/banner.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" />
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta property="og:title" content={metadata.openGraph.title} />
        <meta property="og:description" content={metadata.openGraph.description} />
        <meta property="og:url" content={metadata.openGraph.url} />
        <meta property="og:type" content={metadata.openGraph.type} />
        <meta property="og:image" content={metadata.openGraph.image} />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
